
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.2
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - rabbitmq
      - elasticsearch

  neo4j:
    image: neo4j:5.20.0
    ports:
      - "7474:7474"    # HTTP interface
      - "7687:7687"    # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/helloworld
    volumes:
      - /c/neo4j_docker_data:/data  
  python-service:
    build: ./AI-Model
    container_name: tags-extractor 
    ports:
      - "5000:5000"
